name: Infra-Release

on:
  push:
    branches:
      - main
    paths:
      - infra/**

  workflow_dispatch:

env:
  AZURE_SUBSCRIPTION_ID: "cc934d76-6d72-49cb-a908-81217ad4ae29"
  AZURE_RESOURCE_GROUP: "RG_Donnely.Defoort"

jobs:
  build:
    name: "Validate Templates"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout source code"
        uses: actions/checkout@main

      - name: "Login to Azure"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: "Validate ARM Template"
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          subscriptionId: ${{ env.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP }}
          template: infra/main.bicep
          parameters: infra/dev/main.parameters.json
          deploymentMode: Validate

      - name: "Tar files"
        run: tar -cvf bicep-artifacts.tar ./infra

      - name: "Upload Artifacts"
        uses: actions/upload-artifact@v2
        with:
          name: bicep-artifacts
          path: bicep-artifacts.tar

  release-dev:
    name: "Development"
    environment: Development
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: "Download & Extract Build Artifact"
        uses: actions/download-artifact@v2
        with:
          name: bicep-artifacts

      - name: "Extract Files"
        run: tar -xvf bicep-artifacts.tar

      - name: "Login to Azure"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: "Release Azure Components"
        uses: azure/arm-deploy@v1
        with:
          scope: resourceGroup
          subscriptionId: ${{ env.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP }}
          template: infra/main.bicep
          parameters: infra/dev/main.parameters.json
          deploymentName: Deploy-Demo-Dev-${{ github.run_number }}

  release-tst:
    name: "Test"
    needs: dev
    environment: Test
    runs-on: ubuntu-latest
    steps:
      - name: "Download & Extract Build Artifact"
        uses: actions/download-artifact@v2
        with:
          name: bicep-artifacts

      - name: "Extract Files"
        run: tar -xvf bicep-artifacts.tar

      - name: "Login to Azure"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: "Release Azure Components"
        uses: azure/arm-deploy@v1
        with:
          scope: resourceGroup
          subscriptionId: ${{ env.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP }}
          template: infra/main.bicep
          parameters: infra/tst/main.parameters.json
          deploymentName: Deploy-Demo-Tst-${{ github.run_number }}

  release-prd:
    name: "Production"
    needs: release-dev
    environment: Production
    runs-on: ubuntu-latest
    steps:
      - name: "Download & Extract Build Artifact"
        uses: actions/download-artifact@v2
        with:
          name: bicep-artifacts

      - name: "Extract Files"
        run: tar -xvf bicep-artifacts.tar

      - name: "Login to Azure"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: "Release Azure Components"
        uses: azure/arm-deploy@v1
        with:
          scope: resourceGroup
          subscriptionId: ${{ env.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP }}
          template: infra/main.bicep
          parameters: infra/prd/main.parameters.json
          deploymentName: Deploy-Demo-${{ github.run_number }}
